### ISSUE TITLE
Add functionality to scramble data in date of birth fields

### ISSUE THREAD

**Issue by munsenburner** [kowgli/XrmToolBox.DataverseAnonymizer#7]
Hey Luke,

I have just been trialing the tool, but noticed that there is no option to choose any of the date of birth fields (birthday, birthmonth, birthyear, birthdate) within the contact entity from section one, and no rules for the 'Date' data set in section 2 to allow to scramble this data. Is there the ability to add these to the tool?

Ability to save/load config and the performance with multithreading seem to be really good changes.

**Comment by kowgli** [comment]
Thank you for the input, it's greatly appreciated. In the current version the tool only supports text fields. Adding support for other field types is definitely planned, but I can't say right now when I'll have the time to get back to this project. Hopefully within a few weeks.

**Comment by kowgli** [comment]
The tool now supports additional data types: whole number, float, decimal, currency and dates.
