### ISSUE TITLE
Error Running Tool

### ISSUE THREAD

**Issue by JohnRogerson** [kowgli/XrmToolBox.DataverseAnonymizer#8]
Attempting to use the plugin to anonymize a contact table. I get the following error:
![image](https://github.com/user-attachments/assets/fd6cef37-00b7-49a0-92da-e3395cb0e7bf)

I did think that maybe it's because the org is OnPremise 9.2 and you may be using Dataverse only methods. It has a correct count so is reading ok but doesn't process anything. There's also no log file to troubleshoot.

Appreciate this will be tricky to troubleshoot without a log file. Feature request for log file please. Thanks.

**Comment by kowgli** [comment]
@JohnRogerson 
There were indeed issues with on-prem instances (version <=9.1). They should be fixed in the just published version of the tool (0.5). It should be available in the toolbox within a few hours.
Please let me know if it fixed the error.

**Comment by JohnRogerson** [comment]
That has resolved the issue. Successfully running in our OnPremise environments. Thanks.
